### ISSUE TITLE
Using stack with llvm in non-standard location

### ISSUE THREAD

**Issue by habemus-papadum** [llvm-hs/llvm-hs-kaleidoscope#3]
Hi - thanks for providing this.  I have a custom built llvm installed in a non-standard location (which I do not keep on my path, nor in any environment variable the runtime loader would know to look in by default).  But I do very much like using stack to keep things simple, but till now I have only used it for simple builds -- Do you know how I would modify the stack.yaml and/or `stack build` invocation to deal with this situation to let it know where to find the shared libraries?  Sorry for the newbie question.... cheers, nehal

**Comment by habemus-papadum** [comment]
hmm -- it looks like there are `extra-{include,lib}-dir` options that I should try to use...  I'll close this once I test it out

**Comment by tmcdonell** [comment]
I think `llvm-hs` will at least need to know the location of the `llvm-config` executable for the build. It might be enough to do:

> env PATH=/path/to/custom/install/location:$PATH stack build llvm-hs

**Comment by cocreature** [comment]
@tmcdonell is right, we use `llvm-config` to figure out paths to libraries, headers and so on. So adjusting `PATH` such that it picks up the right `llvm-config` should be all that’s needed.

**Comment by habemus-papadum** [comment]
ahh -- that makes sense, and is much easier... thanks!
